### ISSUE TITLE
face detection

### ISSUE THREAD

**Issue by mourdeveloper** [mWater/OpenCVActivityPlugin#1]
can i use it for face detection ?

**Comment by grassick** [comment]
Absolutely, you just need to integrate the face detection code and you can call it from PhoneGap

**Comment by mourdeveloper** [comment]
where can i get facedetetion using your sample code

**Comment by grassick** [comment]
@mourdeveloper I'm afraid you're on your own. Google OpenCV Face detection to get started! Good luck!
